config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'incidents' => 'pages#index'
  get 'incidents/new' => 'incidents#new'
  get 'incidents/:id' => 'incidents#view'
  get 'incidents/:id/deactivate' => 'incidents#deactivate'
  get 'incidents/:id/edit' => 'incidents#edit'
  get 'incidents/:id/delete' => 'incidents#delete'
  post 'incidents' => 'incidents#create'
  post 'incidents/edit' => 'incidents#edit_incident'
  patch 'incidents/:id/edit' => 'incidents#update'
  delete 'incidents/:id' => 'incidents#delete'
  get 'signout' => 'clearance/sessions#destroy'
  get 'history' => 'pages#history'
  get 'status.svg' => 'pages#current_status_dot', as: 'status_dot'
  post 'subscribers/new' => 'subscribers#create', as: 'create_subscriber'
  get 'subscribers/activate/:activation_key' => 'subscribers#activate', as: 'activate_subscriber'
  get 'subscribers/unsubscribe/:activation_key' => 'subscribers#unsubscribe', as: 'unsubscribe_subscriber'
  if Rails.env == 'development'
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_error_messages.html.erb
<% if @incident.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@incident.errors.count, "error") %>.
      </div>
      <ul>
        <% @incident.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<div class="container-fluid flash">
  <% flash.each do |key, value|%>
     <div class="alert alert-<%=key%>">
       <%= value %>
     <a href="#">
     <span id="toggleflash" style="color: gray; float: right;">x</span>
     </a>
     </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer>
  <% unless request.fullpath == '/history' %>
      <%= link_to '< View previous incidents', history_path %>
  <% end %>
  <div id="poweredby">Proudly powered by <a href="https://github.com/ur0/statusify">Statusify.</a></div>
</footer>

<% cache_if(!signed_in?, "#{cache_key_for_index}-status_dot-#{Incident.where(active: true).count}") do %>
    <%= render partial: 'shared/status_dot' %>
<% end %>

app/views/shared/_incident_controls.html.erb
<% if signed_in? %>
    <%= link_to link_to_incident(incident.id, 'edit') do %>
        <button class="btn btn-warning btn-sm admin-button">Update Incident</button>
    <% end %>
    <%= link_to link_to_incident(incident.id, 'delete'), data: {confirm: 'Are you sure? Deleting an incident is irreversible.'} do %>
        <button class="btn btn-danger btn-sm">Delete Incident</button>
    <% end %>
    <% if incident.active? %>
        <%= link_to(link_to_incident(incident.id, 'deactivate')) do %>
            <button class="btn btn-success btn-sm">Deactivate Incident</button>
        <% end %>
    <% end %>
    <% unless incident.public? %>
        <div class="private-status text-muted">Private Incident</div>
    <% end %>
<% else %>
    <% cache_if(!signed_in?, 'incident-controls-v1') do %>
        <button class="btn btn-sm btn-info" data-toggle="modal" data-target="#subscribe-modal">Subscribe for updates
        </button>
        <div id="subscribe-modal" class="modal fade" role="dialog">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Subscribe to latest alerts from <%= Statusify.app_name %>.</h4>
              </div>
              <div class="modal-body">
                <p>Get notified whenever there's an update to <%= Statusify.app_name %>'s status.</p>
                <%= form_tag create_subscriber_url do %>
                    <%= text_field_tag :email, nil, placeholder: 'Email', class: 'form-control' %>
                    <%= submit_tag('Submit', class: 'btn btn-md btn-success btn-sumbit') %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="navigation-1" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <% if active_incidents.blank? %>
            <div id="header-status"><%= Statusify.app_name %> <span class="up">Status</span></div>
        <% else %>
            <div id="header-status"><%= Statusify.app_name %> <span class="down">Status</span></div>
        <% end %>
      </div>
    </div>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to('Home', root_path) %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
            <li>
              <%= link_to('New incident', '/incidents/new') %>
            </li>
            <li>
              <%= link_to('Sign out', '/signout') %>
            </li>
        <% else %>
            <li>
              <%= link_to('Sign in', '/sign_in') %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_status_dot.html.erb
<% status_dot_tooltip = signed_in? ? "This is your 'Status Dot'. Click it to get its URL." : "Current service status" %>

<div id="status-dot" class="text-center" data-toggle="tooltip" data-placement="top" title="<%= status_dot_tooltip %>">
  <%= image_tag @favicon_path_svg, data: {'toggle': 'modal', target: '#status-dot-modal'} %>
</div>

<% if signed_in? %>
    <div class="modal fade" id="status-dot-modal" tabindex="-1" role="dialog" aria-labelledby="StatusDot">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="statusDotModalLabel">Status Dot</h4>
          </div>
          <div class="modal-body">
            <em>Status dots</em> are awesome embeddable images which can be put anywhere to show your current service
            status.<br/>
            To embed it, just copy the URL below. <br/><br/>
            SVG:
            <pre><%= status_dot_url %></pre>
            Markdown:
            <pre>![<%= Statusify.app_name %> Status](<%= status_dot_url %>)</pre>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
<% end %>